import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} `}>{children}</body>
    </html>
  );
}
